TripId:
  name: tripId
  in: path
  required: true
  description: Mã chuyến đi
  schema:
    type: string
  example: trip_001
OfferId:
  name: offerId
  in: path
  required: true
  description: Mã đề xuất chuyến
  schema:
    type: string
  example: offer_001
CustomerId:
  name: customerId
  in: path
  required: true
  description: Mã khách hàng
  schema:
    type: string
  example: user_customer_001
DriverId:
  name: driverId
  in: path
  required: true
  description: Mã hồ sơ tài xế
  schema:
    type: string
  example: driver_001
VehicleId:
  name: vehicleId
  in: path
  required: true
  description: Mã phương tiện
  schema:
    type: string
  example: vehicle_001
Keyword:
  name: keyword
  in: query
  required: false
  description: Từ khóa tìm kiếm
  schema:
    type: string
    maxLength: 100
